import { Recipe } from './recipe';
import {IndicatorType} from "./recipeDetail";

export const RECIPES: Recipe[] = [
  { id: 11, name: "Pannenkoeken", recipeDetail: { dateOfCreation: new Date("01/07/2018"), imageSrcUrl: "../assets/images/recipes/11.jpg", typeOfDish: IndicatorType.Veg, numberOfPeopleDishSuitableFor: 2, listOfIngredients: ["1/4 cup butter shopping list", "3/4 cup milk", "3/4 cup flour", "3 eggs", "1 cup apple filling (or another flavor)"], cookingInstructions: ["Melt butter in an 8x8 inch pan", "Mix milk, flour, and eggs until smooth", "Pour into pan", "Spoon on apple filling", "Bake at 400 degrees Fahrenheit for 30 minutes", "Serve immediately, it will fall"]}},

  { id: 12, name: "Erwtensoep", recipeDetail: { dateOfCreation: new Date("02/07/2018"), imageSrcUrl: "../assets/images/recipes/12.jpg", typeOfDish: IndicatorType.Veg, numberOfPeopleDishSuitableFor: 8, listOfIngredients: ["2 l. water ", "500 gr. split peas ", "2 onions ", "2 leeks ", "1 celeriac ", "2 potatoes ", "1 carrots ", "bunch of celery ", "pepper and salt ", "150 grams of smoked tofu or vegetarian smoked sausage"], cookingInstructions: ["Rinse the peas well and bring them to the boil in the water. Foam the top as the soup boils. ", "In the meantime, finely chop the onion and the leek in rings. Peel the celeriac and potatoes and cut into cubes. Clean the carrot and cut into strips. Add the vegetables if the peas have cooked for about half an hour. ", "Cook until the peas are cooked and the soup is thick (30 to 60 minutes). ", "Heat the smoked sausage in a pan for the last 10 minutes, cut into slices and add at the end of the cooking time. If you use smoking tofu, cut it into cubes and let it cook with the soup for the last 10 minutes. ", "Cut the celery finely and stir it just before serving by the soup. Season with salt and pepper.", "Serve in large bowls with rye bread smeared with fresh cream cheese."] }},

  { id: 13, name: "Appeltaart", recipeDetail: { dateOfCreation: new Date("03/07/2018"), imageSrcUrl: "../assets/images/recipes/13.jpg", typeOfDish: IndicatorType.Veg, numberOfPeopleDishSuitableFor: 12, listOfIngredients: ["250g plain flour", "175g butter, softened", "80g caster sugar", "2 eggs (1½ for the pastry mixture, ½ for brushing the top)", "1 teaspoon ground cinnamon"], cookingInstructions: ["Mix the flour, softened butter, sugar, cinnamon and 1½ eggs in a bowl. Knead it with your hands to a consistent, smooth dough.", "Roll out ¾ of the dough to cover the bottom and sides of a greased round (24cm) cake tin or spring form tin.", "Preheat the oven to 170 C / Gas 3.", "Peel, core and slice the apples. Mix this with 50g sugar, sultanas and cinnamon. Put this mixture into the prepared cake tin.", "Roll out the remaining dough and cut into long strips, each about 1cm wide. Start with the longest strips and lay the first two in an X in the centre of the pie. Alternate horizontal and vertical strips, weaving them in an over-and-under pattern. Use the shortest strips for the edges of the lattice. If you're having trouble removing the dough from the work surface, roll the strips up like a rug and unroll them onto the pie. Press the ends of the strips firmly to the edge of the pie and trim away any excess dough with a knife. Brush with remaining (beaten) egg.", "Bake for 60-65 minutes, or until pastry is light brown."] }},

  { id: 14, name: "Bami Goreng", recipeDetail: {dateOfCreation: new Date("04/07/2018"), imageSrcUrl: "../assets/images/recipes/14.jpg", typeOfDish: IndicatorType.NonVeg, numberOfPeopleDishSuitableFor: 14, listOfIngredients: [""], cookingInstructions: [""] }},

  { id: 15, name: "Bitterballen", recipeDetail: {dateOfCreation: new Date("05/07/2018"), imageSrcUrl: "../assets/images/recipes/15.jpg", typeOfDish: IndicatorType.NonVeg, numberOfPeopleDishSuitableFor: 40, listOfIngredients: ["1 liter of beef ragout", "5 sheets of gelatin (bag, 12 pieces)", "2 tbsp mustard", "14 slices of tiger bread white", "175 g of wheat flour", "4 medium-sized eggs", "1½ liters of frying oil", "Put these ingredients on my list"], cookingInstructions: ["Heat the ragout and soak the gelatine for 5 minutes in cold water. Squeeze out and allow to dissolve in the ragout. Add the mustard. Put the ragout in the roasting pan. Allow to cool to room temperature in 1 hour. Put in the refrigerator for 3 hours. Preheat the oven to 100 ° C. Roast the bread for 20 minutes in the oven. Let cool and grind in the food processor to coarse breadcrumbs.",
    "Cut the thick ragout (salpicon) into 40 pieces and roll balls. Beat the eggs. Take the balls successively through the flour, the egg and breadcrumbs. Heat the oil in a deep fryer or large pan to 180 ° C. Deep fry 6-8 bitterballen in approx. 4 min. Golden brown. Drain on kitchen paper. Delicious with mustard."] }},

  { id: 16, name: "Poffertjes", recipeDetail: {dateOfCreation: new Date("06/07/2018"), imageSrcUrl: "../assets/images/recipes/16.jpg", typeOfDish: IndicatorType.Veg, numberOfPeopleDishSuitableFor: 10, listOfIngredients: ["1 level teaspoon instant yeast", "1 tablespoon milk", "1 cup buckwheat flour", "1 cup white flour", "2 eggs", "1 teaspoon sugar", "1/2 teaspoon salt", "1 1/4 cups warm milk", "1 tablespoon butter", "Good-quality butter to serve", "Optional: powdered sugar, strawberries, and whipped cream to serve"], cookingInstructions: ["Melt 1 tablespoon butter in a frying or poffertjes pan.", "When the butter starts to sizzle, add teaspoonfuls of the batter in circular movements to create the mini pancakes.", "Turn the poffertjes around as soon as the bottom has set, using two forks.", "Serve the pancakes with the best quality butter you can find and sieved powdered sugar.", "For a sweeter treat, serve these mini pancakes with strawberries, whipped cream and a dusting of powdered sugar."] }},

  { id: 17, name: "Oliebollen", recipeDetail: {dateOfCreation: new Date("07/07/2018"), imageSrcUrl: "../assets/images/recipes/17.jpg", typeOfDish: IndicatorType.Veg, numberOfPeopleDishSuitableFor: 2, listOfIngredients: ["1 (0.6 ounce) cake compressed fresh yeast", "1 cup lukewarm milk", "2 1/4 cups all-purpose flour", "2 teaspoons salt", "1 egg", "3/4 cup dried currants", "3/4 cup raisins", "1 Granny Smith apple - peeled, cored and finely chopped", "1 quart vegetable oil for deep-frying", "1 cup confectioners' sugar for dusting"], cookingInstructions: ["Break up the compressed yeast, and stir into the warm milk. Let stand for a few minutes to dissolve. Sift the flour and salt into a large bowl. Stir the yeast mixture and egg into the flour and mix into a smooth batter. Stir in the currants, raisins and apple. Cover the bowl, and leave the batter in a warm place to rise until double in size. This will take about 1 hour.", "Heat the oil in a deep-fryer, or heavy deep pan to 375 degrees F (190 degrees C). Use 2 metal spoons to shape scoops of dough into balls, and drop them carefully into the hot oil.", "Fry the balls until golden brown, about 8 minutes. The doughnuts should be soft and not greasy. If the oil is not hot enough, the outside will be tough and the insides greasy. Drain finished doughnuts on paper towels and dust with confectioners' sugar. Serve them piled on a dish with more confectioners' sugar dusted over them. Eat them hot if possible."] }},

  { id: 18, name: "Hollandse nieuwe haring", recipeDetail: {dateOfCreation: new Date("08/08/2018"), imageSrcUrl: "../assets/images/recipes/18.jpg", typeOfDish: IndicatorType.NonVeg, numberOfPeopleDishSuitableFor: 8, listOfIngredients: ["1 ei", "1 el mosterd", "1 el rodewijnazijn", "2 el zonnebloemolie", "1 kleine zure augurk (potje 340 g)", "2 haringen (duopak Hollandse Nieuwe met gesnipperde ui)", "3 el platte peterselie (fijngesneden)", "1 stronk witlof"], cookingInstructions: ["Boil the egg in 8 minutes. Let scare, peel and cut. Mix the mustard with the vinegar. Beat the oil with a whisk drop by drop so that a bound vinaigrette is formed. Season with salt and pepper.", "Slice the pickles very small and mix with the onion of the herring through the vinaigrette. Mix the parsley and vinaigrette through the egg.", "Cut the pegs into 16 pieces. Cut the bottom of the chicory and remove 8 beautiful leaves. Spoon some of the parsley-egg salad in each leaf and top with 2 pieces of herring. Serve immediately."] }},

  { id: 19, name: "Stamppot", recipeDetail: { dateOfCreation: new Date("09/07/2018"), imageSrcUrl: "../assets/images/recipes/19.jpg", typeOfDish: IndicatorType.NonVeg, numberOfPeopleDishSuitableFor: 4, listOfIngredients: ["Ground beef and pork", "mustard", "ketjap manis", "salt", "ground black pepper", "ground nutmeg", "eggs", "bread crumbs", "butter"], cookingInstructions: ["Mix these ingredients in a bowl by hand until well combined and sticky:", "500 grams of ground beef and pork mix, 2 tbs mustard, 2 tbs ketjap manis, ¼ ts salt, ½ ts ground black pepper, 1 ts ground nutmeg, ⅓ cup bread crumbs, and 2 eggs.", "*tip: You can replace 2 tbs ketjap manis with 2 tbs soy sauce and ½ tbs brown sugar", "Divide the mixture into 4 large balls.", "", "Heat up a covered pot or pan with over medium high heat.", "Add ¼ cup butter and wait until it turns brown.", "Cook the meatballs until all sides are golden brown.", "Turn down the heat and simmer for about 25-30 minutes. Flip occasionally until thoroughly cooked.", "Take the meatballs out of the pot out and set aside.", "Add ¼ cup water to the pot and cook over low heat to make gravy. You can add 1 ts flour to make it sticky."] }},

  { id: 20, name: "Sate", recipeDetail: { dateOfCreation: new Date("10/07/2018"), imageSrcUrl: "../assets/images/recipes/20.jpg", typeOfDish: IndicatorType.NonVeg, numberOfPeopleDishSuitableFor: 8, listOfIngredients: ["380 g chicken fillet", "6 el ketjap manis", "2 tsp sambal oelek", "2 cloves of garlic", "175 g peanut butter with pieces of nut (pot à 350 g)", "150 ml of tap water", "2 tablespoon ginger syrup", "1 tsp ground ginger", "3 tbsp ground coconut"], cookingInstructions: ["Cut the chicken into pieces of 3 cm. Mix the chicken with almost all sweet soy sauce and half of the sambal in a bowl. Press half of the garlic on top. Allow the chicken to marinate in the refrigerator for at least 1 hour. Let the skewers soak in water for at least 30 minutes.", "Put the peanut butter, the rest of the soy sauce and the rest of the sambal into a saucepan. Squeeze the rest of the garlic above it. Pour in the water and ginger syrup. Add the ginger powder. Bring to the boil while stirring. Stir until a smooth sauce.", "Thread the chicken on the skewers and grill for about 15 minutes on the barbecue. Sprinkle with the coconut and serve with the peanut sauce."] }}
];
