import {IndicatorType} from "./recipe";
import { Recipe } from './recipe';

export const RECIPES: Array<Recipe> = [
  {id: 11, name: "Pannenkoeken", typeOfDish: IndicatorType.Veg, details: [{id: 11, dateOfCreation: new Date(), numberOfPeopleDishSuitableFor: 2}], ingredients: [{id: 11, ingredient: "1/4 cup butter shopping list"}, {id: 12, ingredient: "3/4 cup milk"}, {id: 13, ingredient: "3/4 cup flour"}, {id: 14, ingredient: "3 eggs"}, {id: 15, ingredient: "1 cup apple filling (or another flavor)"}], instructions: [{id: 11, instruction: "Melt butter in an 8x8 inch pan"}, {id: 12, instruction: "Mix milk, flour, and eggs until smooth"}, {id: 13, instruction: "Pour into pan"}, {id: 14, instruction: "Spoon on apple filling"}, {id: 15, instruction: "Bake at 400 degrees Fahrenheit for 30 minutes"}, {id: 16, instruction: "Serve immediately, it will fall"}]},

  {id: 12, name: "Erwtensoep", typeOfDish: IndicatorType.Veg, details: [{id: 21, dateOfCreation: new Date(), numberOfPeopleDishSuitableFor: 12}], ingredients: [{id: 21, ingredient: "2 l. water"}, {id: 22, ingredient: "500 gr. split peas"}, {id: 23, ingredient: "2 onions"}, {id: 24, ingredient: "2 leeks"}, {id: 25, ingredient: "1 celeriac"}, {id: 26, ingredient: "2 potatoes"}, {id: 27, ingredient: "1 carrots"}, {id: 28, ingredient: "bunch of celery"}, {id: 29, ingredient: "pepper and salt"}, {id: 30, ingredient: "150 grams of smoked tofu or vegetarian smoked sausage"}], instructions: [{id: 21, instruction: "Rinse the peas well and bring them to the boil in the water. Foam the top as the soup boils."}, {id: 22, instruction: "In the meantime, finely chop the onion and the leek in rings. Peel the celeriac and potatoes and cut into cubes. Clean the carrot and cut into strips. Add the vegetables if the peas have cooked for about half an hour."}, {id: 23, instruction: "Cook until the peas are cooked and the soup is thick (30 to 60 minutes)."}, {id: 24, instruction: "Heat the smoked sausage in a pan for the last 10 minutes, cut into slices and add at the end of the cooking time. If you use smoking tofu, cut it into cubes and let it cook with the soup for the last 10 minutes."}, {id: 25, instruction: "Cut the celery finely and stir it just before serving by the soup. Season with salt and pepper."}, {id: 26, instruction: "Serve in large bowls with rye bread smeared with fresh cream cheese."}]},

  {"id":13,"name":"Appeltaart","typeOfDish":IndicatorType.Veg,"details":[{"id":13,"dateOfCreation":new Date(),"numberOfPeopleDishSuitableFor":12}],"ingredients":[{"id":31,"ingredient":"test ingredient"}],"instructions":[{"id":31,"instruction":"test instruction"}]},

  {"id":14,"name":"Bami Goreng","typeOfDish":IndicatorType.NonVeg,"details":[{"id":14,"dateOfCreation":new Date(),"numberOfPeopleDishSuitableFor":14}],"ingredients":[{"id":41,"ingredient":"test ingredient"}],"instructions":[{"id":41,"instruction":"test instruction"}]},

  {"id":15,"name":"Bitterballen","typeOfDish":IndicatorType.Veg,"details":[{"id":15,"dateOfCreation":new Date(),"numberOfPeopleDishSuitableFor":40}],"ingredients":[{"id":51,"ingredient":"test ingredient"}],"instructions":[{"id":51,"instruction":"test instruction"}]}
];
